Repository kanakmi/Detective-Discord, pull requests merged in 2022-10, with the labels that each got.

#9 Updated README and certain files in order to run locally
  .gitignore
  README.md
  bot.py
  requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#8 Update bot.py
  README.md
  bot.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#10 Update README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#13 Updated Bot.py and README.md
  README.md
  bot.py
Labels: enhancement, hacktoberfest

#16 Updated contributing guidelines
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
